name: run tests
on: 
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'     
jobs:
  Windows:
    name: Run Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@develop

    - name: Run dir command
      run: dir
